### ISSUE TITLE
Some messages are not shown because double quotes

### ISSUE THREAD

**Issue by sebilasse** [KamiKillertO/inquirer-select-directory#1]
Hey there,
see line 199/200

It _SHOULD_ read
```js
message += chalk.dim('\n(Use "/" key to search this directory)');
message += chalk.dim('\n(Use "-" key to navigate to the parent folder');
```

In general I would recommend to use simple quotes for the JS code `'` instead of `"` ...
You don't need to escape `"` in the text then (as above), also https://github.com/airbnb/javascript#strings

**Comment by sebilasse** [comment]
Apart from that : Awesome idea ... 👍

**Comment by KamiKillertO** [comment]
Indeed I've made a mistake thank you 😃 .
I'll will correct it 👍

**Comment by KamiKillertO** [comment]
Done!
Thank you again ^^
