### ISSUE TITLE
Bug: Press "." key to select the current directory - does NOT work

### ISSUE THREAD

**Issue by axe312ger** [KamiKillertO/inquirer-select-directory#14]
Hey there,

the readme is saying:
> Press "." key to select the current directory.

But this option does not show up and is not working. I can not find anything about this in the code, also.

Any plans to implement/fix this?

All the best,
Benedikt

**Comment by KamiKillertO** [comment]
Indeed this feature is missing 😖. I'll fix it as soon as possible 😄

**Comment by axe312ger** [comment]
awesome 😍
